### ISSUE TITLE
Blog post - Culinary consumption

### ISSUE THREAD

**Issue by angelicambg** [trendecon/media-content#1]
Dear @SLegge2020, @izmartinez, @vzei, @ronaldindergand, @christophsax, @uwethuemmel , 

Please find below a draft for a new short blog post written by Alexander @a1exgo . We'll wait for your comments to post it on the website.
_____

**Culinary consumption patterns before, during and after the lockdown: Will the changes remain?**

On 27 August 2020, the State Secretariat for Economic Affairs (SECO) announced the historic 8.2% quarter-on-quarter decline in Swiss economic output during the second quarter of 2020. In their economic note, SECO’s economists explain that private consumption in particular has suffered an unprecedented slump. Past crises have shown that private consumption has saved the economy from worse developments. In the current COVID 19 crisis, private consumption was unable to play this role due to health policy measures.

Ever since the outbreak of the pandemic and during the lockdown, US economists have been speculating that current consumption habits could change not only in the short term but also in the medium or long term. In particular, the use of online shops for everyday shopping has been given a further boost by the lockdown restrictions, which could well ring in a turnaround in the retail sector.

However, whether the composition of the consumer basket will change with shopping opportunities (e.g. via online shops instead of going to supermarkets) is another question. Whether and how the demand for goods changes can be investigated more closely by taking a look at specific consumer categories. In the following, we will look at consumption categories that are among the most everyday things in life: food.

With trendEcon we can take a closer look at the search queries for specific consumer goods that were presumably influenced by the pandemic and the lockdown. We have chosen the terms _Restaurant_, _Bar_, _Rezept_ and _Sauerteig_ as search terms.

The first pair of terms (“Restaurant” and “Bar”; dashed lines) reflects search queries related to going out. If we look at the temporal course of the search queries, it is apparent that the two terms were hardly googled during the lockdown and only regained their usual level towards the beginning of June 2020. Interestingly, we also see that the term “Restaurant” was searched for even more after than before the lockdown. On the one hand, this can be a compensatory effect, where people longed to enjoy a prepared meal instead of cooking themselves. But also a widespread uncertainty is conceivable; we are much more likely to check whether a restaurant is even open before we visit it. In the above-mentioned economic note, the SECO also reports compensatory effects in private consumption, but does not expect full compensation for the losses of the first half of the year.

The other terms (“Rezept” and “Sauerteig”, solid lines) stand for activities that we associate with cooking at home. The development of search queries with “Rezept” shows that people typically look for recipes during holiday season in late December. However, the lockdown seems to have turned restaurant goers into cooks. Surprisingly, Swiss people have also taken time for more complex procedures such as the cultivation of sourdough (NZZ, June 2020). The time series on the search behavior for “Sauerteig” documents a huge hype between March and May, which came to an abrupt end after the first easing of the lockdown rules, which could be due to the fact that employees left their home offices again.

A look at the current state shows that the search terms shown have reached old levels again. Concerns about the effects of the second infection wave or job security may, however, continue to affect consumer behavior in the coming weeks. Therefore, we will see whether private consumption will be able to stabilize the declining economic output in the coming quarter. We are skeptical, however, whether sourdough will be part of this near future.

![image](https://user-images.githubusercontent.com/38508957/91765655-a06ab600-ebd9-11ea-86db-cd3dde83c440.png)

--

**Kulinarische Konsummuster vor, während und nach dem Lockdown: Veränderungen, die bleiben?**

Am 27. August 2020 verkündete das Staatssekretariat für Wirtschaft (SECO) den historischen Rückgang der Schweizer Wirtschaftsleistung während des zweiten Quartals 2020 gegenüber dem Vorquartal um 8.2%. Die Ökonomen des SECO erklären in ihrer Konjunkturnotiz, dass insbesondere der private Konsum einen noch nie dagewesenen Einbruch erlitten hat. In vergangenen Krisen hat sich gezeigt, dass der private Konsum die Wirtschaft vor schlimmeren Entwicklungen bewahrt hat. Dieser Rolle konnte der Konsum in der gegenwärtigen COVID-19-Krise aus gesundheitspolitischen Massnahmen nicht nachkommen.

Schon seit Ausbruch der Pandemie und während des Lockdowns spekulieren US-amerikanische Ökonomen, dass die bisherigen Konsumgewohnheiten sich nicht nur kurzfristig sondern auch mittel- und langfristig verändern könnten. Insbesondere die Nutzung von Online-Shops für alltägliche Einkäufe habe durch die Ausgeh-Restriktionen einen weiteren Schub erhalten, welche durchaus eine Zeitenwende im Einzelhandel einläuten könnte.

Ob sich aber die Zusammensetzung des Konsumkorbs mit den Einkaufsmöglichkeiten, z.B. eben über Online-Shops statt im Supermarkt, verändert, ist eine andere Frage. Ob und wie sich die Nachfrage nach Gütern verändert, lässt sich mit einem Blick auf einzelne Konsumrubriken genauer erforschen. Im Folgenden wollen wir uns Konsumrubriken widmen, die zu den alltäglichsten des Lebens gehören: dem Essen.

Mit trendEcon können wir die Suchanfragen nach spezifischen Konsumgütern, welche mutmasslich durch die Pandemie und dem Lockdown beeinflusst wurden, genauer betrachten. Als Suchbegriffe haben wir die Begriffe «Restaurant» und «Bar» sowie «Rezept» und «Sauerteig» gewählt.

Das erste Begriffspaar («Restaurant» und «Bar»; gestrichelte Linien) spiegelt Suchanfragen wider, die mit dem Ausgehen zusammenhängen. Betrachten wir den zeitlichen Verlauf der Suchanfragen, fällt auf, dass die beiden Begriffe während des Lockdowns kaum mehr gegoogelt wurden und erst wieder gegen Anfang Juni 2020 das übliche Niveau erlangten. Interessanterweise sehen wir auch, dass der Begriff «Restaurant» nach den Lockerungsphasen sogar stärker gesucht wurde als vor dem Lockdown. Dies kann einerseits ein Kompensationseffekt sein, wobei man sich danach danach sehnte sich bekochen zu lassen anstatt selbst zu kochen. Aber auch eine weit verbreitete Unsicherheit ist denkbar, so dass wir in der Schweiz vor einem Restaurant viel eher nachsehen, ob dieses überhaupt geöffnet ist. In der angesprochenen Konjunkturnotiz berichtet das SECO ebenfalls von Kompensationseffekten im Konsum aus, rechnet aber nicht mit einer vollständigen Kompensation der Ausfälle der ersten Jahreshälfte.

Die anderen Begriffe («Rezept» und «Sauerteig», durchgezogene Linien) stehen für Aktivitäten, die wir mit dem Kochen zuhause in Verbindung bringen. Die Entwicklung der Suchanfrage «Rezept» lässt erkennen, dass es typischerweise während der Festtage im Dezember ins Suchfeld eingegeben wird. Der Lockdown scheint aber aus den Restaurantgänger*innen Köch*innen gemacht zu haben. Erstaunlicherweise haben Schweizer*innen sich auch Zeit für aufwändigere Verfahren wie die Kultivierung von Sauerteigen genommen (NZZ, Juni 2020). So dokumentiert die Zeitreihe über das Suchverhalten nach «Sauerteig» einen gewaltigen Hype zwischen März und Mai, der nach den ersten Lockerungen sein jähes Ende fand, was daran liegen könnte, dass Arbeitnehmende ihre Home-Offices wieder verliessen.

Ein Blick auf den heutigen Stand zeigt, dass die erläuterten Suchbegriffe wieder alte Niveaus erreicht haben. Sorgen über die Auswirkungen der zweiten Infektionswelle oder Jobsicherheit können sich jedoch auch in den kommenden Wochen auf das Konsumverhalten auswirken. Es bleibt also zu beobachten, ob der Konsum im kommenden Quartal die rückläufige Wirtschaftsleistung zu stabilisieren vermag. Wir sind jedoch skeptisch, ob der Sauerteig Teil dieser nahen Zukunft sein wird.

**Comment by SLegge2020** [comment]
Well written piece! Three short comments:

(1) "Past crises have shown that private consumption has saved the economy from worse developments." -> you probably want to briefly state the reasoning behind this: GDP = C + I + G + NX ----> the volatility of I drives the biz cycle, C is pretty stable. How have the four components of GDP in Switzerland fared in Q1 and Q2 of 2020?

(2) There is some overlap with my proposed article "Shifts in Demand", posted here on Github:
https://github.com/trendecon/gtrendecon/issues/58
But that is okay for me.

(3) You may want to cite / refer to Malmendier & Shen -- maybe better in a separate blog post:
https://eml.berkeley.edu/~ulrike/Papers/Draft_MalmendierShen_15aug2019.pdf


@angelicambg Will you upload my post(s)? Maybe we can discuss this bilaterally via email? Thanks!

**Comment by ronaldindergand** [comment]
I like this text a lot, too!
Generally: One thing that will continue to interest is wether and how much the second wave affects people's behavior or not. This is where our indicators add much value in my view as all other data is often more delayed. I suggest to continue focusing on that issue in the near future. 
Please let us know as soon it is posted so we can tweet it.

**Comment by a1exgo** [comment]
Thanks to both,
@SLegge2020 : Thanks for the hint -- I will add a sentence with regard to the reasoning you mentioned. Sorry for the overlap; I was not aware of the process with raising issues here at git (First, I thought the update works via merge requests that are reviewed). I will adapt.
@ronaldindergand : Yes, I will do some amendments Stefan proposed and will send a mail. 

I think we should fix a process that notifies our big-influence tweeters such that they can spread.

**Comment by a1exgo** [comment]
Dear @angelicambg : I will post Friday morning directly and close this issue. Pls let me know, if I should wait or you want to do it :)

**Comment by angelicambg** [comment]
@a1exgo sure, you can post it, just remember to create a new branch and I'll check it and merge.

**Comment by a1exgo** [comment]
Dear @ronaldindergand @izmartinez @uwethuemmel @christophsax @vzei , new blog posts are up: https://www.trendecon.org/#deutsch and https://www.trendecon.org/#english (@SLegge2020 and I appreciate your possible tweets ;)) #issueclosed.
