### ISSUE TITLE
Blog post - Football is back! But what about the fans?

### ISSUE THREAD

**Issue by a1exgo** [trendecon/media-content#2]
Dear all (@SLegge2020 @christophsax @uwethuemmel @izmartinez @vzei @angelicambg @ronaldindergand ), I wrote a new blog article. Happy to receive feedback, which I could implement swiftly. Ideally, the article is published this weekend as it related to the new football season ;) kind regards, alex

----------------- ENGLISH
**Football is back! But what about the fans?**

This weekend marks the start of the new football season in Switzerland and Germany. Due to the Corona crisis, the Swiss Football League (SFL) has adjusted its match schedule for the 2020/2021 season. In addition to postponements, football fans in this country will also be affected by new regulations to which they will have to adapt. But are the fans ready fort hat and have they already bought their tickets?

Last month, the Swiss Football Association was already working on a draft for a protection concept (https://www.football.ch/portaldata/27/resources/dokumente/diverses/Covid_Schutzkonzept_August2020_DE.pdf) on how football clubs should treat their fans in a Corona-compliant manner. In addition to individual rules (only appear free of symptoms, keep your distance, wash your hands), guidelines that are the responsibility of the clubs must also be followed. For example, a maximum of 1000 in the stadium must not be exceeded until the end of October. According to the Federal Council's announcement of 12 August, from October onwards, in principle, more than 1000 people are permitted at major events. More importantly, however, the protection of citizens and thus also of stadium-goers is the responsibility of the cantons. In addition, it may be necessary to wear masks on the stadium grounds, which in turn depends on the various cantonal Covid-19 rules. Thus, depending on the stadium and the canton on which it is located, fans have to adapt to regional conditions.

It is complicated, indeed! If we use our trendEcon indicator for cultural events, we can see a level shift since the beginning of the year. It is striking that this shift is unique in the last four years. The indicator thus illustrates an uncertainty about the attendance of events in general. Although football can only remotely be associated with cultural events, this uncertainty also plays a role for fans.

The trendEcon data illustrate that the uncertainty regarding a stadium visit is high relative to recent years. The time series of the search term "Spielplan" (match schedule) reveals an interesting pattern: During major football tournaments (World and European Championships), the search behavior shoots up, while activity remains constant during the rest of the time. Only this year the level has dropped to an unprecedented low. If we look at the term "season ticket", a similar picture emerges: Every second half of the year the demand for season tickets increases. This year, however, there has been a crash of this demand, which on average has settled at a lower level. Uncertainty about this year's fan joy has prompted, for instance, the Swiss champion BSC YB to temporarily suspend season ticket sales (https://www.bscyb.ch/news?nID=12105). Such measures also contribute to the downward trend in season ticket sales. 

We have also taken a look at the search terms "Fallzahlen" (incidents) and "Maskenpflicht" (mask requirement) and clearly see increased search activity for both terms. In particular, the term "Fallzahlen" has reached a new record level, which far exceeds the level of the first wave of infections in spring.

The data of our analysis illustrate the uncertainty of Swiss football fans. Due to these uncertainty about the second infection wave and possible new restrictions, we assume that the number of visitors to football stadiums will remain low. In general, these are uncertainties that affect all Swiss people: How is the second wave developing? Is a mask required at public venues? Ultimately, these are questions that could have an impact not only on the sales of stadium tickets but also on general consumer spending.
![image](https://user-images.githubusercontent.com/48187315/93576263-fb065f00-f99a-11ea-937a-48951f2d477d.png)

----------------- **GERMAN**
**Der Ball rollt wieder – Werden Fans live dabei sein?**
An diesem Wochenende beginnt die neue Fussballsaison in der Schweiz und Deutschland. Aufgrund der Corona-Krise hat die Swiss Football League (SFL) den Spielplan für die Saison 2020/2021 angepasst. Neben terminlichen Verschiebungen kommen dem Fussballfan hierzulande jedoch auch neue Regelungen entgegen, auf welche es sich neu einzustellen gilt. Doch sind die Fans bereit und haben sie ihre Eintrittskarten bereits organisiert?

Bereits im vergangenen Monat hat der Schweizerische Fussballverband  an einer Vorlage für ein Schutzkonzept(https://www.football.ch/portaldata/27/resources/dokumente/diverses/Covid_Schutzkonzept_August2020_DE.pdf) gearbeitet, wie Fussballvereine ihre Fans Corona-konform zu behandeln haben. Neben individuellen Regeln (nur symptomfrei erscheinen, Abstand halten, Hände waschen) müssen auch Richtlinien eingehalten werden, die im Verantwortungsbereich der Vereine liegen. So dürfen sich z.B. bis Ende Oktober maximal 1000 Personen im Stadion befinden. Gemäss der bundesrätlichen Ankündigung vom 12. August sind ab Oktober grundsätzlich wieder mehr als 1000 Leute bei Grossveranstaltungen zugelassen. Wichtiger aber ist, dass der Schutz der Bürger und somit auch der Stadiongänger bei den Kantonen liegt. Weiter kann eine Maskenpflicht auf dem Stadiongelände anfallen, welche wiederum von den unterschiedlichen kantonalen Covid-19-Regeln abhängen. Je nach Kanton und Fussballstadion müssen sich Fans an die regionalen Gegebenheiten anpassen.

Es ist also kompliziert! Wenn wir unseren trendEcon-Indikator für kulturelle Events heranziehen, lässt sich eine Niveauverschiebung seit Beginn des Jahres erkennen. Auffällig ist, dass diese Verschiebung einmalig ist in den letzten vier Jahren. Der Indikator illustriert mithin eine Unsicherheit über den Besuch von Veranstaltungen allgemein. Obwohl Fussball nur entfernt mit kulturellen Events in Verbindung gebracht werden kann, spielt diese Unsicherheit auch bei den Fans eine Rolle.

Die Daten von trendEcon veranschaulichen, dass die Unsicherheit bezüglich eines Stadionbesuchs relativ zu den letzten Jahren gross ist. Die Zeitreihe des Suchbegriffs «Spielplan» lässt ein interessantes Muster erkennen: Während grossen Fussballturnieren (Welt- und Europameisterschaft) schiesst das Suchverhalten hoch, während die Aktivität in der übrigen Zeit konstant bleibt. Nur in diesem Jahr ist das Niveau auf ein noch nie erreichtes Tief gesunken. Wenn man auf den Begriff «Saisonkarte» blickt, zeigt sich ein ähnliches Bild: In jede zweiten Jahreshälfte steigt die Nachfrage nach Saisonkarten. In diesem Jahr gab es einen Absturz dieser Nachfrage, die sich im Schnitt auf einem tieferen Niveau einpendelt. Die Unsicherheit über das diesjährige Stadionglück veranlasste z.B. den Schweizer Meister BSC YB den Jahreskartenverkauf temporär auszusetzen (https://www.bscyb.ch/news?nID=12105). Auch solche Massnahmen tragen dazu bei, dass die Tendenz der Saisonkarten-Verkäufe nach unten zeigt. 

Wir haben auch einen Blick auf die Suchbegriffe «Fallzahlen» und «Maskenpflicht» geworfen und erkennen klar eine erhöhte Suchaktivität nach den beiden Begriffen. Insbesondere der Begriff «Fallzahlen» erreicht einen neuen Rekordwert, welcher das Level der ersten Infektionswelle im Frühling weit überragt.

Die Daten unserer Analyse verbildlichen die Unsicherheiten von Schweizer Fussballfans. Aufgrund dieser Unsicherheiten und über die zweite Welle und möglichen neuen Restriktionen gehen wir davon aus, dass die Besuchszahlen in Fussballstadien niedrig bleiben werden. Generell handelt es sich um Unsicherheiten, die alle Schweizer betreffen: Wie entwickelt sich die zweite Welle? Muss eine Maske in der Öffentlichkeit getragen werden? Es sind letztlich Fragen, die sich nicht nur auf den Verkauf von Stadionkarten, sondern auf die generelle Konsumfreude auswirken könnten.

**Comment by SLegge2020** [comment]
Passt thematisch sehr gut. Ich würde nur einen kurzen abschliessenden Absatz hinzufügen, welche "eine Antwort gibt" auf die Frage "Werden die Fans dabei sein?".

Inhaltlich kommt mir einzig in den Sinn: Wechseln die Fans von Stadionbesuch auf Sky/DAZN/etc?

**Comment by a1exgo** [comment]
Danke, @SLegge2020 , ich werde die gestellte Frage noch beantworten. Die Idee mit Sky, DAZN ist interessant. Ich dachte mir, dies vielleicht in einem späteren Post aufzunehmen (dieser hier ist schon lang genug, glaube ich).
