### ISSUE TITLE
Demand for new payment methods

### ISSUE THREAD

**Issue by a1exgo** [trendecon/media-content#4]
Dear all (@SLegge2020 @christophsax @ronaldindergand @angelicambg @vzei @izmartinez @ninamuehlebach @uwethuemmel )

I believe there is this notion of increasing demand for new payment methods. Especially since the outbreak of the covid-19 crisis, people seem to refrain from cash payments. I have also found this input article: [EY](https://www.ey.com/en_bh/banking-capital-markets/how-covid-19-is-reshaping-retail-payments-in-europe)

What is your opinion on that. What do think could have gained attention from Google searchers? Are there any related trends that we could pick up? Thanks for sharing your thoughts.

Possible search queries:
**consumer side:**
- bitcoin wallets?
- twint?
- credit card?
**seller's side:**
- Datatrans
- Payrexx
- Sumup

**Comment by SLegge2020** [comment]
Hi, interesting topic.
Search item that come to my mind include "Twint", "Kreditkarten", "Kreditkarten Vergleich", "kontaktlos bezahlen", "Apple Pay Schweiz".
If we could plot some Google trends together with data on credit card usage in Switzerland - that would be a cool blog post.

**Comment by a1exgo** [comment]
Hi @SLegge2020 ; I love the idea comparing google trends with credit card usage -- will look around for them!

**Comment by christophsax** [comment]
Perhaps better to keep this discussions at https://github.com/trendecon/project/issues (formerly https://github.com/trendecon/gtrendecon/issues), so we have all issues at one place. There are some other ideas discussed there.

Any progress on that? Otherwise, please close or reassign. Closed is not deleted, and can always be reopened.

**Comment by a1exgo** [comment]
Hey @christophsax , I will take up the topic again. (was very busy the last weeks, but now I am free). I will open the issue at the correct place!
